# Generated by Django 5.1.1 on 2024-09-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_block_chatroom_mute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mute',
            name='room',
        ),
    ]
